/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.kirunews.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-07-2008
 * 
 * XDoclet definition:
 * @struts.form name="changeLocaleForm"
 */
public class ChangeLocaleForm extends ActionForm {
	/*
	 * Generated fields
	 */

	private static final long serialVersionUID = 1L;
	
	/** lang property */
	private String language;
	
	private String path;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the lang.
	 * @return String
	 */
	public String getLanguage() {
		return language;
	}

	/** 
	 * Set the lang.
	 * @param lang The lang to set
	 */
	public void setLanguage(String language) {
		this.language = language;
	}

	public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}
}