/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.kirunews.struts.action;

import java.io.IOException;
import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.kirunews.struts.form.ChangeLocaleForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-07-2008
 * 
 * XDoclet definition:
 * @struts.action path="/changeLocale" name="changeLocaleForm" input="/form/changeLocale.jsp" scope="request" validate="true"
 */
public class ChangeLocaleAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) 
				throws IOException {
		System.out.println("ChangeLocaleAction-RequestURL: " + request.getRequestURL());
		ChangeLocaleForm changeLocaleForm = (ChangeLocaleForm) form;// TODO Auto-generated method stub
		
		String language = changeLocaleForm.getLanguage();
		System.out.println("language: " + language);
		if(language.equals("fr")) {
			Locale.setDefault(Locale.FRANCE);
			setLocale(request, Locale.FRANCE);
		} else if(language.equals("hu") || language.equals("hu_HU")) {
			Locale.setDefault(new Locale("hu"));
			setLocale(request, new Locale("hu"));
		} else if(language.equals("en")) {
			Locale.setDefault(Locale.UK);
			setLocale(request, Locale.UK);
		} else {
			Locale.setDefault(Locale.UK);
			setLocale(request, Locale.UK);
		}
		System.out.println("getLocale: " + getLocale(request) + ", default: " + Locale.getDefault());
		response.sendRedirect(request.getContextPath() + "/" + changeLocaleForm.getPath() + ".do");
		return null;
	}
}